info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@
    environment: ${spring.profiles.active}

spring:
  profiles:
    active: dev
  application:
    name: ${info.build.name}-${spring.profiles.active}
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
debug: false
server:
  port: 9000
  tomcat:
    max-connections: 100
    max-threads: 100